import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';

const retailTypes = new Set(['Finished Product', 'Multi-step System / Kit']);
// Existing live products absent from v10, approved for removal from the active catalog.
const legacyIds = [
  '00000000-0000-4000-8000-000000000303', '5dc7b109-ea4f-4f99-a33a-134181c7009b',
  '84825bfc-3c14-48c4-b6eb-3768a2a54803', '8dc3ec64-2f18-4e61-bbe1-f69273f9f4b3',
  '29f8cff8-163f-43ab-9130-06315e1a0a44', '54fab881-31d9-4760-ad94-3e124c913b94',
];
export function table(snapshot, name) {
  const sheet = snapshot.sheets.find((s) => s.title === name);
  if (!sheet) throw new Error(`Missing sheet: ${name}`);
  const headers = sheet.values[2];
  return sheet.values.slice(3).map((raw, i) => ({
    row: i + 4, raw, fields: Object.fromEntries(headers.map((h, j) => [h, String(raw[j] ?? '')])),
  }));
}

export function prepare(snapshot) {
  const records = table(snapshot, 'Products_Canonical');
  const ids = new Set();
  for (const { fields: r } of records) {
    if (!/^SKP-\d+$/.test(r.product_id) || ids.has(r.product_id)) throw new Error(`Invalid/duplicate ID: ${r.product_id}`);
    if (!r.product_name || !r.entity_type) throw new Error(`Missing identity: ${r.product_id}`);
    if (retailTypes.has(r.entity_type) && !r.brand) throw new Error(`Missing retail brand: ${r.product_id}`);
    ids.add(r.product_id);
  }
  const shiftedRows = [];
  const reviews = table(snapshot, 'Review_Queue').map(({ row, raw, fields }) => {
    if (!/^REV-\d+$/.test(raw[0] ?? '')) {
      // Known source defect: 8 cells under a 9-column header; preserve the raw row in the snapshot.
      if (raw.length !== 8 || !['OPEN', 'RESOLVED', 'PARTIALLY RESOLVED'].includes(raw[6])) {
        throw new Error(`Unrecognized review layout at row ${row}`);
      }
      fields = Object.fromEntries(Object.keys(fields).map((h, i) => [h, i === 0 ? `V10-ROW-${String(row).padStart(4, '0')}` : String(raw[i - 1] ?? '')]));
      shiftedRows.push(row);
    }
    if (!['OPEN', 'RESOLVED', 'PARTIALLY RESOLVED'].includes(fields.status)) throw new Error(`Invalid review status at row ${row}`);
    return { id: `v10-row-${String(row).padStart(4, '0')}`, source_row: row, fields, status: fields.status };
  });
  if (new Set(reviews.map((r) => r.id)).size !== reviews.length) throw new Error('Duplicate review IDs');
  const links = table(snapshot, 'Product_Master_Links');
  if (new Set(links.map((r) => r.fields.link_id)).size !== links.length) throw new Error('Duplicate master link IDs');
  const orphanLinks = links.filter((r) => !ids.has(r.fields.product_id));
  const eligible = records.filter((r) => retailTypes.has(r.fields.entity_type));
  return {
    records: records.map((r) => r.fields), reviews,
    links: links.filter((r) => ids.has(r.fields.product_id)).map((r) => r.fields),
    report: { source: snapshot.source, canonicalRecords: records.length, retailRecords: eligible.length,
      nonRetailRecords: records.length - eligible.length, reviewItems: reviews.length, repairedReviewRows: shiftedRows,
      archiveLegacyProductIds: legacyIds,
      duplicateReviewIds: reviews.filter((r, i) => reviews.findIndex((other) => other.fields.review_id === r.fields.review_id) !== i).map((r) => ({ row: r.source_row, sourceReviewId: r.fields.review_id })),
      masterLinks: links.length - orphanLinks.length,
      quarantinedMasterLinks: orphanLinks.map((r) => ({ row: r.row, id: r.fields.link_id, sourceId: r.fields.product_id })),
      policy: 'New retail products are unpublished and need review. Matching existing product IDs, visibility, descriptions and ingredients are preserved. Six legacy products absent from v10 are archived per user request. All source fields remain admin-only evidence. Non-retail records stay outside products. No ingredient parsing or clinical rule activation.' },
  };
}

function sqlJson(value) { return "'" + JSON.stringify(value).replaceAll("'", "''") + "'::jsonb"; }

export function buildSql(snapshot, prepared) {
  const digest = createHash('sha256').update(JSON.stringify(snapshot)).digest('hex');
  return `-- Generated by scripts/catalog-import.mjs. Review data/catalog/import-report.json before applying.
-- Snapshot SHA-256: ${digest}
begin;
set local standard_conforming_strings = on;
-- Serialize imports; existing product identity and wardrobe references must remain stable.
select pg_advisory_xact_lock(hashtext('substrate-catalog-import'));
insert into public.catalog_imports(id, source_url, source_modified_at, fetched_at, snapshot)
values ('v10-pilot-batch-1', ${sqlJson(snapshot.source)}->>'url', (${sqlJson(snapshot.source)}->>'modifiedAt')::timestamptz,
  (${sqlJson(snapshot.source)}->>'fetchedAt')::timestamptz, ${sqlJson(snapshot)}) on conflict (id) do nothing;
do $import$
declare r jsonb; brand_uuid uuid; product_uuid uuid; candidates uuid[]; brand_slug text; product_label text; cat text;
begin
  for r in select value from jsonb_array_elements(${sqlJson(prepared.records)}) loop
    if exists (select 1 from public.catalog_records where source_id = r->>'product_id') then continue; end if;
    product_uuid := null;
    if r->>'entity_type' in ('Finished Product', 'Multi-step System / Kit') then
      brand_slug := trim(both '-' from regexp_replace(lower(r->>'brand'), '[^a-z0-9]+', '-', 'g'));
      select array_agg(id) into candidates from public.brands where slug = brand_slug or lower(name) = lower(r->>'brand');
      if coalesce(cardinality(candidates), 0) > 1 then raise exception 'Ambiguous brand: %', r->>'brand'; end if;
      brand_uuid := candidates[1];
      if brand_uuid is null then
        insert into public.brands(name, slug) values (r->>'brand', brand_slug) returning id into brand_uuid;
      end if;
      product_label := r->>'product_name';
      if lower(left(product_label, length(r->>'brand') + 1)) = lower((r->>'brand') || ' ') then
        product_label := substr(product_label, length(r->>'brand') + 2);
      end if;
      -- Exact normalized name or alias only: strength/format siblings must never be fuzzy-merged.
      select array_agg(p.id) into candidates from public.products p where p.brand_id = brand_uuid and exists (
        select 1 from unnest(array[p.name] || p.aliases) as names(n)
        where regexp_replace(lower(n), '[^a-z0-9]+', '', 'g') in (
          regexp_replace(lower(product_label), '[^a-z0-9]+', '', 'g'),
          regexp_replace(lower(r->>'product_name'), '[^a-z0-9]+', '', 'g'))
      );
      if coalesce(cardinality(candidates), 0) > 1 then raise exception 'Ambiguous product: %', r->>'product_id'; end if;
      product_uuid := candidates[1];
      if product_uuid is null then
        cat := case left(r->>'primary_master', 2) when '01' then 'cleanser' when '02' then 'moisturizer'
          when '04' then 'spf' when '06' then 'retinoid' when '09' then 'exfoliant' else 'other' end;
        insert into public.products(brand_id, name, slug, category, aliases, status, catalog_visible)
        values (brand_uuid, product_label, lower(r->>'product_id'), cat, array[r->>'product_name'], 'needs_review', false)
        returning id into product_uuid;
      end if;
    end if;
    insert into public.catalog_records(source_id, product_id, import_id, entity_type, fields)
    values (r->>'product_id', product_uuid, 'v10-pilot-batch-1', r->>'entity_type', r);
  end loop;
end;
$import$;
insert into public.catalog_master_links(id, source_id, fields)
select r->>'link_id', r->>'product_id', r from jsonb_array_elements(${sqlJson(prepared.links)}) r on conflict (id) do nothing;
insert into public.catalog_reviews(id, source_row, fields, status)
select r->>'id', (r->>'source_row')::integer, r->'fields', r->>'status'
from jsonb_array_elements(${sqlJson(prepared.reviews)}) r on conflict (id) do nothing;
update public.products p set archived_at = now(), catalog_visible = false, status = 'draft'
where p.id in (select jsonb_array_elements_text(${sqlJson(legacyIds)})::uuid)
  and p.archived_at is null
  and not exists (select 1 from public.catalog_records r where r.product_id = p.id);
commit;
`;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const snapshot = JSON.parse(readFileSync(process.argv[2] ?? 'data/catalog/source-v10.json', 'utf8'));
  const prepared = prepare(snapshot);
  writeFileSync('data/catalog/import-report.json', JSON.stringify(prepared.report, null, 2) + '\n');
  writeFileSync('data/catalog/import-v10.sql', buildSql(snapshot, prepared));
  console.log(JSON.stringify(prepared.report, null, 2));
}
